name: Deploy on Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container: bluebuilder/azure:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login
        run: cd .azure && ./setup.sh --ci-login
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create infrastructure
        run: cd .azure && ./infra.sh create
      - name: Build project
        run: cd .azure && ./build.sh
      - name: Deploy project
        run: cd .azure && ./deploy.sh
